language: node_js
matrix:
  fast_finish: true
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: npm
  email: npm@cozycloud.cc
  skip_cleanup: true
  api_key:
    secure: RJ/2Os0d+d1aFC/BfOhLHv0QmFR6fFi1y+HbtZGOy7UH61fyb+7xoyd9NMcBatO1RnjURhlsZSh7Dmipcc+41WUWEnmPnxxRNBsXDzBO00Y/emAgWQnmRklwzwfe3BLW74ir/oGUG5o+9IzkLGxlsx8mFRblgXv6IhQQs6Acx+A4CTsyYYZwemFrNRNK8Da2m/O3mRf9BQPhlgxGgXTWjJ5V3rwFbDJjvTRvcx2/ndKxGI3Kfon2quaMQQ9EV6AehQIWCa9/xCme/7CdClN8n8ESg0V6ssdThPicPGqkP2bLyfBQH/DM0txFSjrQzccH79iJhtp6LpRskXC61G5wPs/dWDNczajSfcwd3TDeB7Rhia1fkDdqwvSVbGgx27I6ZCcCBoVH77GwWFHe0WfA3705PRIYWTEEzYZ7CliL+On6KrQ9z3C0sOsvSIoCDknbGnFPoDLQLLaB/96y2fyjxXHvZ8am6NTRjWjDgNM6dLf41fdSMUSgieCI1bjeHGXsR1Puj+0s12GnxkSr6l2oMKfPeKadbWK7aXKbKdNpBcv2twTkXjHaC+KF1IPorGW7+mxp5GRFH6sdarHUzwEL8DXMXlr0PEh5EO8RP10LT9R8ty8RnF+ctBvKsOGZ9JVxl8EZCeAeSToRGO303k0oa922S61cwIUdrDrKQz8adlY=
  on:
    tags: true
    repo: cozy/cozy-app-publish
