language: node_js
matrix:
  fast_finish: true
node_js:
- '6'
cache:
  yarn: true
  directories:
  - node_modules

deploy:
  provider: npm
  email: npm@cozycloud.cc
  skip_cleanup: true
  api_key:
    secure: ''
  on:
    tags: true
    repo: cozy/cozy-app-publish
