language: node_js
matrix:
  fast_finish: true
node_js:
- '8'
cache:
  yarn: true
  directories:
  - node_modules
deploy:
  provider: npm
  email: npm@cozycloud.cc
  skip_cleanup: true
  api_key:
    secure: H0rylfvxMZoDBPlh4YZ/rmU43GV7xbQfAY4k/weLQPUMDnZNYs+MaeLw6HvUzjJtby5o97umTXYL8eydzwetCo+nbmWrh1Am3mNgMV2Yx8MlGNP+Mz6rQT2FdCb1vNkiHkV6yyvAlyFgGr0XZ1mTxR8puwFe4D42bwDfIZiRN4cXxsOFNRBhFY4kitfyReOG5COtOg9uJvmOXFPvwHkjHhQKuLgr/RzV/xAXJldHyxVNMPtfxYyT8wqUxwyFAyMKyd6GfGbrn7AJc8HTbyFEo1ibyyinonh7x1q61vxvwkBhBzK2TdTxJkvnnidoTduUQP/4UHplxsOZBxedEelqy9NmlyHbUlRA3WmlVeN5wDeiNNOABQPMgqoLhA5kLZ/nrG5fnsWxJ0EBQYWpkFKRDx5Gl5V+19yfz5TLR/Om+zWNicevt/T1XPzepnNXfIiW11l+rtlT5RFxnE08fPbMVx+91XF6+zDF7LvpLsNmVCU64he+QxravCXg54muvHoIdMm8cVfy7+RFE48fTKPcXVQkH9kUPiobj63GihRio/5uSsssMex+O4x5PGQf3zYAjOCs9+av21V7Z+XwRSuTqyaPqJmVcD3KWw8u0wLG0UQxcK0l8qJAQKycIBxHv+se62PGi8wCAsmex7Ol3ruGz8tXQQyj6x+aVlE8k7Hwsqk=
  on:
    tags: true
    repo: cozy/cozy-app-publish
